### ISSUE TITLE
bug in dim_names?/ Update documentation

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/rray#105]
At dim_names.r line: 90 we have:

`dim_names.double <- function(x) {
  list(names(x))
}`

This function (which is copied to other base vector types) doesnt follow the behavior described in the documentation when names of the vector are NULL.

``` r
library(rray)
dim_names(c(1.2,3.4))
#> [[1]]
#> NULL
```

<sup>Created on 2019-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Shouldn't it be something like:

`dim_names.double <- function(x) {
  list(c(names(x),character()))
} `
for example?

**Comment by DavisVaughan** [comment]
Ah, I need to update the documentation. It's doing the right thing. If there are no names it should return a list of NULL that is as long as the dimensionality of x. NULL is the more standard value for "missing" in this case
