### ISSUE TITLE
can't install properly, thanks for advice.

### ISSUE THREAD

**Issue by GreenEric** [DavisVaughan/rray#107]
After watching ur introduction of "rray", I would like to install it.
when installing the package, I kept receiving messages like following

```
> devtools::install_github("DavisVaughan/rray")
Downloading GitHub repo DavisVaughan/rray@master
tar.exe: Archive entry has empty or unreadable filename ... skipping.
**(many lines)**
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Error exit delayed from previous errors.
Error: Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar.exe -zxf "C:\Users\eric1\AppData\Local\Temp\RtmpYnJelP\file4d947cdb548d.tar.gz" -C "C:/Users/eric1/AppData/Local/Temp/RtmpYnJelP/remotes4d94490d5d41"’ returned error code 1
2: In system(cmd, intern = TRUE) :
  running command 'tar.exe -ztf "C:\Users\eric1\AppData\Local\Temp\RtmpYnJelP\file4d947cdb548d.tar.gz"' had status 1

```

I also tried to clone the master file, and install in `zip` way, but seems not working as it can't find the package.

```
> library(`rray-master`)
Error in library(`rray-master`) : 不存在叫‘rray-master’这个名字的程辑包
```

Please advise, and many thanks,
Eric

**Comment by DavisVaughan** [comment]
Are you on a Windows? Mac?

Whatever you tried to do with cloning doesn't look to be the right approach.

Can you post the full output of running the `devtools::install_github()`?

**Comment by GreenEric** [comment]
Thanks for prompt reply.  I'm on win10, and the result is as what I described at 1st chunk. 
Many lines of "tar.exe: Archive entry has empty or unreadable filename ... skipping." And follows "Error: Does not appear to be an R package (no DESCRIPTION)"
I guess it's bcs nothing is downloaded.

**Comment by DavisVaughan** [comment]
I believe this is your issue. Can you try and set the environment variable as said here? https://github.com/r-lib/devtools/issues/1939

**Comment by DavisVaughan** [comment]
Closing as i am pretty sure the above comment was your issue.
