### ISSUE TITLE
rray() dimnames preservation

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/rray#109]
I am surprised by the fact that the **rray()** constructor doesn't preserve the dimnames of the matrix/array or even  rray it is passed in.
Perhaps it was just a provisional decision that you might want to consider again.
But if not, I can't figure it out the reasons behind it.
I understand that when a different **dim** is suplied, the names must be discarded, but when there are no conflicts between both dims (or no new dim is given), keeping the existing dimnames seems desirable.
Supose you substituted the **if** sentence in line 41 of **rray.r** with this one:
```
    if (is_null(dim_names)) {
      dim_names <- if (identical(dim,vec_dim(x))){
                      dim_names(x) 
                   } else {
                      new_empty_dim_names(vec_size(dim))
                   }
    } 
```
What would be wrong?

**Comment by DavisVaughan** [comment]
`rray()` is meant to be the "helper" constructor for the lower level `new_rray()`. As such, it should only use names provided by the `dim_names` argument. It essentially helps create completely new rray objects. `matrix()` and `array()` use similar conventions. If you want to coerce from an existing matrix/array, and keep dimension names, you should use `as_rray()`.

**Comment by juangomezduaso** [comment]
Oh, of course. Thanks
