### ISSUE TITLE
Bug in rray_any()

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/rray#140]
``` r
library(rray)
rray_any(rray(c(FALSE,NA),1:2))
#> <rray<lgl>[,1][1]>
#>      [,1]
#> [1,] TRUE
```

<sup>Created on 2019-05-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
I was checking what happens when NA are present when I found this (bug, I suppose). 
Would it be useful to have some **na.rm** parameter to allow the seek of "definitely" TRUEs?

**Comment by DavisVaughan** [comment]
There isn't good support for missing values whatsoever in rray yet. I'm waiting on xtensor to fix a few bugs with their `xoptional` container, which deals with missing values, before I try adding them to rray.

**Comment by juangomezduaso** [comment]
ok , I see. Thanks.
 Feel free to close or keep the issue at your convenience

**Comment by DavisVaughan** [comment]
I'll close, but referenced in #21 so I won't forget when the time comes
