### ISSUE TITLE
Is `rray_split()` actually using `MARGIN`?

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/rray#161]
I've hit an issue twice now where it feels like `rray_split()`'s axes argument is inconsistent with what it is actually returning. It feels like it is doing `MARGIN`. Perhaps this is due to the fact that the xtensor/numpy version of split only allows for 1 axis, so they didn't have this inconsistency.

I think the order needs to be "complemented" before being passed to `rray_multi_split()`

Especially when thinking about `rray_map()` or something like a split-apply-combine idea, the current split approach feels wrong

**Comment by juangomezduaso** [comment]
I dont know whether this is related with what you have detected, but I think that there is a problem with split_dim_names() that might be tripping you up:
``` r

library(rray)

(  rr <- rray(1:6, 2:3, list(A=c("a1","a2"),B=c("b1","b2","b3")))  )
#> <rray<int>[,3][6]>
#>     B
#> A    b1 b2 b3
#>   a1  1  3  5
#>   a2  2  4  6
rray_split(rr,2:1)
#> [[1]]
#> <rray<int>[,1][1]>
#>     B
#> A    b1
#>   a1  1
#> 
#> [[2]]
#> <rray<int>[,1][1]>
#>     B
#> A    b2
#>   a2  2
#> 
#> [[3]]
#> <rray<int>[,1][1]>
#>     B
#> A    b3
#>   a1  3
#> 
#> [[4]]
#> <rray<int>[,1][1]>
#>     B
#> A    b1
#>   a2  4
#> 
#> [[5]]
#> <rray<int>[,1][1]>
#>     B
#> A    b2
#>   a1  5
#> 
#> [[6]]
#> <rray<int>[,1][1]>
#>     B
#> A    b3
#>   a2  6
```

<sup>Created on 2019-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
Values seem ok but names are wrong
You can try this modified function:
``` r

library(rray)
library(rlang)
  rr <- rray(1:6, 2:3, list(A=c("a1","a2"),B=c("b1","b2","b3")))  
  split_dim_names2 <- function(dim_names, axes, n) {
    
    # Prep container with existing one
    # (some names might already be correct)
    new_dim_names <- rep_len(list(dim_names), prod(n))
    
    for (i in seq_along(axes)) {
      axis <- axes[i]
      n_i <- n[i]
      
      # Nothing to do if there aren't existing names
      axis_nms <- dim_names[[axis]]
      if (is.null(axis_nms)) {
        next
      }
      
      # Split the existing axis names into `n_i` pieces
      by <- length(axis_nms) / n_i
      split_axis_nms <- new_list(n_i)
      k <- 1L
      for (j in seq_len(n_i)) {
        split_axis_nms[[j]] <- axis_nms[k:(k + by - 1)]
        k <- k + by
      }
      
      # Assign the split names to their correct location
      # in the output
      # times to repeat each name subset
      rep_each= prod(n[seq_along(axes)> i])
      axis_names_list <- split_axis_nms[rep(seq_len(n_i),
                                            times= length(new_dim_names)/rep_each,
                                            each=rep_each)
                                        ]
      for (j in seq_along(new_dim_names)) {
        new_dim_names[[j]][[axis]] <- axis_names_list[[j]]
      }
    }
    
    new_dim_names
  }
  split_dim_names2(dim_names(rr),2:1,3:2)
#> [[1]]
#> [[1]]$A
#> [1] "a1"
#> 
#> [[1]]$B
#> [1] "b1"
#> 
#> 
#> [[2]]
#> [[2]]$A
#> [1] "a2"
#> 
#> [[2]]$B
#> [1] "b1"
#> 
#> 
#> [[3]]
#> [[3]]$A
#> [1] "a1"
#> 
#> [[3]]$B
#> [1] "b2"
#> 
#> 
#> [[4]]
#> [[4]]$A
#> [1] "a2"
#> 
#> [[4]]$B
#> [1] "b2"
#> 
#> 
#> [[5]]
#> [[5]]$A
#> [1] "a1"
#> 
#> [[5]]$B
#> [1] "b3"
#> 
#> 
#> [[6]]
#> [[6]]$A
#> [1] "a2"
#> 
#> [[6]]$B
#> [1] "b3"
```

<sup>Created on 2019-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DavisVaughan** [comment]
I think `rray_split()` is definitely doing the wrong thing right now. This approach below is much more intuitive and aligns with how a split-apply-combine approach would match up with the reducers. @juangomezduaso there is definitely something wrong with the current dim names function, but hopefully it will become significantly less complex when I implement this new approach tomorrow.

The idea is that `axes` specified here are the axes that keep their sizes. The other axes are reduced to size 1. (i.e. if `axes = 1` and it started with 2 rows, each individual split will also have 2 rows)

``` r
library(rray)

axes_to_margin <- function(axes, dims) {
  if (is.null(axes)) {
    integer()
  }
  else {
    setdiff(seq_len(dims), axes)
  }
}

rray_split2 <- function(x, axes) {
  rray_split(x, axes = rev(axes_to_margin(axes, rray_dims(x))))
}

x <- array(1:8, c(2, 2, 2))

# (2, 2, 2) -> (2, 1, 1)
rray_split2(x, 1)
#> [[1]]
#> , , 1
#> 
#>      [,1]
#> [1,]    1
#> [2,]    2
#> 
#> 
#> [[2]]
#> , , 1
#> 
#>      [,1]
#> [1,]    3
#> [2,]    4
#> 
#> 
#> [[3]]
#> , , 1
#> 
#>      [,1]
#> [1,]    5
#> [2,]    6
#> 
#> 
#> [[4]]
#> , , 1
#> 
#>      [,1]
#> [1,]    7
#> [2,]    8

# (2, 2, 2) -> (1, 2, 1)
rray_split2(x, 2)
#> [[1]]
#> , , 1
#> 
#>      [,1] [,2]
#> [1,]    1    3
#> 
#> 
#> [[2]]
#> , , 1
#> 
#>      [,1] [,2]
#> [1,]    2    4
#> 
#> 
#> [[3]]
#> , , 1
#> 
#>      [,1] [,2]
#> [1,]    5    7
#> 
#> 
#> [[4]]
#> , , 1
#> 
#>      [,1] [,2]
#> [1,]    6    8

# (2, 2, 2) -> (1, 1, 2)
rray_split2(x, 3)
#> [[1]]
#> , , 1
#> 
#>      [,1]
#> [1,]    1
#> 
#> , , 2
#> 
#>      [,1]
#> [1,]    5
#> 
#> 
#> [[2]]
#> , , 1
#> 
#>      [,1]
#> [1,]    2
#> 
#> , , 2
#> 
#>      [,1]
#> [1,]    6
#> 
#> 
#> [[3]]
#> , , 1
#> 
#>      [,1]
#> [1,]    3
#> 
#> , , 2
#> 
#>      [,1]
#> [1,]    7
#> 
#> 
#> [[4]]
#> , , 1
#> 
#>      [,1]
#> [1,]    4
#> 
#> , , 2
#> 
#>      [,1]
#> [1,]    8

# (2, 2, 2) -> (2, 2, 1)
rray_split2(x, c(1, 2))
#> [[1]]
#> , , 1
#> 
#>      [,1] [,2]
#> [1,]    1    3
#> [2,]    2    4
#> 
#> 
#> [[2]]
#> , , 1
#> 
#>      [,1] [,2]
#> [1,]    5    7
#> [2,]    6    8

# (2, 2, 2) -> (2, 2, 2)
# equal to rray_split2(x, c(1, 2, 3))
rray_split2(x, NULL)
#> [[1]]
#> , , 1
#> 
#>      [,1] [,2]
#> [1,]    1    3
#> [2,]    2    4
#> 
#> , , 2
#> 
#>      [,1] [,2]
#> [1,]    5    7
#> [2,]    6    8

# (2, 2, 2) -> (1, 1, 1)
# don't hold any axis fixed
rray_split2(x, integer())
#> [[1]]
#> , , 1
#> 
#>      [,1]
#> [1,]    1
#> 
#> 
#> [[2]]
#> , , 1
#> 
#>      [,1]
#> [1,]    2
#> 
#> 
#> [[3]]
#> , , 1
#> 
#>      [,1]
#> [1,]    3
#> 
#> 
#> [[4]]
#> , , 1
#> 
#>      [,1]
#> [1,]    4
#> 
#> 
#> [[5]]
#> , , 1
#> 
#>      [,1]
#> [1,]    5
#> 
#> 
#> [[6]]
#> , , 1
#> 
#>      [,1]
#> [1,]    6
#> 
#> 
#> [[7]]
#> , , 1
#> 
#>      [,1]
#> [1,]    7
#> 
#> 
#> [[8]]
#> , , 1
#> 
#>      [,1]
#> [1,]    8
```

<sup>Created on 2019-05-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by DavisVaughan** [comment]
This is what I mean when I say that this new approach aligns the split-apply-combine method with the reducers:

``` r
library(rray)

axes_to_margin <- function(axes, dims) {
  if (is.null(axes)) {
    integer()
  }
  else {
    setdiff(seq_len(dims), axes)
  }
}

rray_split2 <- function(x, axes) {
  rray_split(x, axes = rev(axes_to_margin(axes, rray_dims(x))))
}

x <- array(1:8, c(2, 2, 2))

library(purrr)

rray_generic_reducer <- function(.x, .f, ..., .axes) {
  res <- map_dbl(rray_split2(x, .axes), .f, ...)
  rray:::keep_dims(res, .x, .axes)
}

rray_mean(x, 1)
#> , , 1
#> 
#>      [,1] [,2]
#> [1,]  1.5  3.5
#> 
#> , , 2
#> 
#>      [,1] [,2]
#> [1,]  5.5  7.5
rray_generic_reducer(x, mean, .axes = 1)
#> , , 1
#> 
#>      [,1] [,2]
#> [1,]  1.5  3.5
#> 
#> , , 2
#> 
#>      [,1] [,2]
#> [1,]  5.5  7.5

rray_mean(x, c(1, 2))
#> , , 1
#> 
#>      [,1]
#> [1,]  2.5
#> 
#> , , 2
#> 
#>      [,1]
#> [1,]  6.5
rray_generic_reducer(x, mean, .axes = c(1, 2))
#> , , 1
#> 
#>      [,1]
#> [1,]  2.5
#> 
#> , , 2
#> 
#>      [,1]
#> [1,]  6.5
```

<sup>Created on 2019-05-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by DavisVaughan** [comment]
Can also rewrite the c split function using a custom version of the xtensor split function. It doesn't quite do what we want without some extra work

**Comment by juangomezduaso** [comment]
In my view, the parameter of the current rray_split() can be seen more like  an  **axes** rather than a **margin**. Like the former, we specify dimensions that are going to be different in the results (collapsed to one or to the value in **n** if we have it). And the axes parameter in rray_split2() can be seen as a **MARGIN** if we imagine that we would divide the input for every combination of these dimensions, applyed a function, that in this case would be splitting to individual cells allong all remaining dims, and finally combined again the MARGIN structure. Of course things dont happen this way, but conceptually I find it sound.
Now, if rray_generic_reducer() wants to have an axis kind of parameter, it could call current rray_split() but passing to it an **axes** parameter that would be the complementary of its own  **.axes** parameter. It may seem confusing, but I think we are mixing two different "split, apply combine" porcesses here: The one of the reducer and the one of the splitter (if it were implemented in terms of this pattern).
And the sets of dimensions happen to be complementaries.

In a less philosophical line: What about the **n** argument? I don't know how useful it can be, but it is clear that in the rray_split2() option it would be very weird to have it.

Finally, my "third cent" on this issue: Regarding end user ease of use, I think that if we have a YEAR x STATE matrix M, and we did:
 M %>% rray_split(YEAR)
 I would expect one rray for every year we had in M (and not the list of time series of the states). But this is just a very subjective impresion of course

**Comment by DavisVaughan** [comment]
Okay, I'm convinced that the current split behavior is more like `axes` than `margin`, and that is the correct thing to do:

Right now, doing something like splitting a `(2, 3, 5)` array along `axes = 1` should return a list of sub arrays where each subarray has its 1st axis "reduced" to length 1, i.e. `(1, 3, 5)`. This matches the behavior of reducers. 

Doing `axes = c(2, 3)` should result in 15 sub arrays of shape `(2, 1, 1)`.

PR #163 has a few changes that improve performance, and dim name handling. The `map()`ing of `vec_restore()` is still going to make another copy, but eventually there are plans to improve that as well so it won't have to make a copy when it restores attributes.

**Comment by DavisVaughan** [comment]
The other change in that PR is that now you don't have to "reverse" the axes when you split over multiple axes. So `axes = c(2, 3)` does something that is probably more intuitive. You don't have to do `c(3, 2)`.

Since I rewrote `xt::split()` in that PR, I have thrown out the ability to use `n` for now. I'm not sure how useful it will be, and it just complicates things at the moment.
