### ISSUE TITLE
Is a custom vec_restore() needed?

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/rray#162]
Would be great to use default vctrs one for speed

**Comment by DavisVaughan** [comment]
We shouldn't really need one, but currently things like `rray(TRUE) + TRUE` are problematic beacause the common type is `rray(logical())` but the actual result type is `integer()` and when you do `vec_restore(integer(), rray(logical()))` the default method of `vec_restore.vctrs_vctr()` doesn't like that the types are different.

**Comment by DavisVaughan** [comment]
We can take the `vec_type2()` of the common type and the return type of the actual function. So we get the common type of `rray(logical())` and `integer()` to get `rray(integer())` as the restore type

**Comment by DavisVaughan** [comment]
Harder than I thought because this doesn't work in a comparison function. `>` should always return a logical. Say you do `vec_type_common(res, x, y)`. That will give you the right outer type (rray or not) but likely won't return a logical inner type. You can try to do an inner cast on that result, but then you lose the outer type. Alternatively, we _know_ it should return a logical, but how do we know what the outer type is?

**Comment by juangomezduaso** [comment]
I don't understand what is the point of calling vec_restore() , be it rray's or vctrs's one, from the comparison and arithmetic functions. As you already take care of everything (dimnames, internal casting, etc) on the functions that do the job, Wouldn't it suffice to assign the class attribute (vctrs_rray_<TYPE OF RESULT>, vctrs_rray and  vctrs_vctr) to the final result?

**Comment by DavisVaughan** [comment]
See #170 also! The original motivation was so you could call the actual underlying function of `rray_add()` with 2 base R matrices and get another matrix back rather than an rray. But 99% of the time you will call it using `+` in which case method dispatch ensures it is only called when one of the two inputs is an rray, meaning the output must be an rray.

**Comment by DavisVaughan** [comment]
#173
