### ISSUE TITLE
What should rray_max_pos() return?

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/rray#185]
I don't understand why rray_max_pos() returns a rray object. I may be missing some insigth here, but I wonder if it just leaked  from xtensor (I dont know what is its meaning there). 
On the other hand, the powerfull ( and hard to understand ) numpy array indexes are not part of rray, and hence my doubs.

**Comment by DavisVaughan** [comment]
its the same thing as `argmax()` from numpy/xtensor but I didn't like that name

why wouldn't it return an rray/array (depending on the input)?

**Comment by juangomezduaso** [comment]
Well there is no real reason why not. But I expected a bare vector of indexes with no dimensional structure and cann't imagine what it's alignment along one of the dimensions can be used for.
If at the end there were neither  any problem nor any utility it would be just a a matter of tastes.
I'll think about it. Thanks

**Comment by juangomezduaso** [comment]
Ouch! I was mistaken.Having only considered a matrix example didnt realize that in general it is a multidimensional result! Sorry

**Comment by DavisVaughan** [comment]
No problem! It's a useful function for interactive use but I'm not sure what you really use it for after you find the positions

**Comment by juangomezduaso** [comment]
Perhaps for things like this:
``` r
library(rray)
#> Warning: package 'rray' was built under R version 3.5.3
x<- rray(c(2,4,3,3,  5,6,7,2,  5,7,2,8,  3,2,2,1,  3,2,4,5),  4:5)

1:4 == rray_max_pos(x,1)
#> <rray<lgl>[,5][20]>
#>       [,1]  [,2]  [,3]  [,4]  [,5]
#> [1,] FALSE FALSE FALSE  TRUE FALSE
#> [2,]  TRUE FALSE FALSE FALSE FALSE
#> [3,] FALSE  TRUE FALSE FALSE FALSE
#> [4,] FALSE FALSE  TRUE FALSE  TRUE

# Or in general:
whereAreTheAxisMaxs <- function(x,axis) seq_len(dim(x)[[axis]]) == rray_max_pos(x,axis)
```

<sup>Created on 2019-05-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wolfv** [comment]
you can imagine having multiple arrays with the same shape, and filtering all based on the max value of one of those using argmax / max_pos.

**Comment by juangomezduaso** [comment]
I see. Thanks!
