### ISSUE TITLE
Rewrite `rray_unique_()` functions

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/rray#186]
I think they need to be rethought a bit, but we can't do exactly what we do with the duplicate ones. I think they only work on 1 axis, but might have to be specified as `fixed_axis` because otherwise I think you would have to specify them as `axes = c(2, 3)` every time.

**Comment by juangomezduaso** [comment]
I like very much the coherence and the documentation of this function, which contrasts with that of base R, where, let apart the consistency aspect,  I had reported this issue on duplicated() manual:
https://stat.ethz.ch/pipermail/r-help/2019-May/462620.html
not resolved in my opinion.
Perhaps I am wrong, but I have filled another one today about unique() in the same line
