### ISSUE TITLE
Helpers for rowwise / colwise creation

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/rray#199]
rray_row(...)

Recycles and coerces inputs to common type
rray_row(x = 1:5, y = 2)

rray_col(...)

**Comment by DavisVaughan** [comment]
This is like a tibble () equivalent

**Comment by DavisVaughan** [comment]
Maybe more general, you just specify the axis you create it along?

**Comment by DavisVaughan** [comment]
Always at least 2D? If we generalize to have an axis argument then we have the issue of the rray_row() example above just being a 1D result, unless all inputs are at least 2D

Maybe just let it be a special method for creating 2D rrays

**Comment by juangomezduaso** [comment]
I dont understand what these would do, but if they are what I think:
 Isnt rray_col() just a rray_cbind()? And rray_row() could be done with rray_transposed(rray_cbind()) ?

**Comment by DavisVaughan** [comment]
Yea actually I hadn't thought about `rray_row()` being a transpose of a cbind. That does what I want. It isn't quite as simple as just using `rray_rbind()` for that case, and that was my confusion.

``` r
library(rray)
library(rlang)

rray_col <- function(...) {
  rray_cbind(...)
}

rray_row <- function(...) {
  rray_transpose(rray_col(...))
}

# not as simple as this for rray_row()
# because I want them to be 2D
rray_rbind(1:5, 6:10, 2)
#>  [1]  1  2  3  4  5  6  7  8  9 10  2

# this is what I want for rray_col(),
# so yea rray_cbind() works
rray_col(1:5, 6:10, 2)
#>      [,1] [,2] [,3]
#> [1,]    1    6    2
#> [2,]    2    7    2
#> [3,]    3    8    2
#> [4,]    4    9    2
#> [5,]    5   10    2

# this makes sense
rray_row(1:5, 6:10, 2)
#>      [,1] [,2] [,3] [,4] [,5]
#> [1,]    1    2    3    4    5
#> [2,]    6    7    8    9   10
#> [3,]    2    2    2    2    2

# i guess this makes sense for rray_row()
# (it obviously makes sense for the underlying operations)
# maybe it should restrict to 1D inputs, not sure
rray_row(array(1:5, c(5, 1, 1)), 6:10, 2)
#> , , 1
#> 
#>      [,1] [,2] [,3]
#> [1,]    1    6    2
#> 
#> , , 2
#> 
#>      [,1] [,2] [,3]
#> [1,]    2    7    2
#> 
#> , , 3
#> 
#>      [,1] [,2] [,3]
#> [1,]    3    8    2
#> 
#> , , 4
#> 
#>      [,1] [,2] [,3]
#> [1,]    4    9    2
#> 
#> , , 5
#> 
#>      [,1] [,2] [,3]
#> [1,]    5   10    2
```

<sup>Created on 2019-05-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by DavisVaughan** [comment]
this doesn't make too much sense though. not sure what the result with the names should actually be

``` r
library(rray)
library(rlang)

rray_row <- function(...) {
  rray_transpose(rray_cbind(...))
}

rray_row(x = array(1:5, c(5, 1, 1)), 6:10, 2)
#> , , 1
#> 
#>      x    
#> [1,] 1 6 2
#> 
#> , , 2
#> 
#>      x    
#> [1,] 2 7 2
#> 
#> , , 3
#> 
#>      x    
#> [1,] 3 8 2
#> 
#> , , 4
#> 
#>      x    
#> [1,] 4 9 2
#> 
#> , , 5
#> 
#>      x     
#> [1,] 5 10 2
```

<sup>Created on 2019-05-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by juangomezduaso** [comment]
My point was more a reflection about the need for these new functions rather than propose an implementation. But dont trust me too much in this repect, as I have an excesive tendecy to  terseness

**Comment by DavisVaughan** [comment]
for now i'll leave these out of the first version. i don't think they are that necessary / useful
