### ISSUE TITLE
reshape is keeping metanames

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/rray#201]
I think this doesnt make much sense and should better be droped just like dimnames are.
Cases with singleton dimensions like:
 ( 2 , 3 )  -> ( 1 , 2 , 3 )
  "A" "B"   ->  "A" "B" ""
sould be, if at all:
  "A" "B"   ->  ""  "A" "B" 
Or:
( 2 , 1 , 3 )  -> ( 2 , 3 )
 "A" "B" "C"  -> "A" "B" 
should be:
  "A" "B" "C"  ->"A" "C" 
But there is no general solution

**Comment by DavisVaughan** [comment]
it should probably just drop them if the axis size changes.

so 

```
( 2 , 3 ) -> ( 1 , 2 , 3 )
"A" "B" -> "" "" ""
```

```
( 2 , 1 , 3 ) -> ( 2 , 3 )
"A" "B" "C" -> "A" ""
```
