### ISSUE TITLE
role of t.vctrs_rray() 

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/rray#202]
I dont get the role t.vctrs_rray() method is suposed to play. 
The abort message when dims(x) > 2 states that we are not using rray_transpose().
But if it is supposed to be base t() working as usual on rray objects: Why don't do the "wrong" conversion of (n)->(1,n) that users of base t() would expect?

I think that xtensor's "transpose" concept is base R "aperm". Both default to dimension flipping with no exceptions, and so, in 1D, we have: (n) ->(n)
R's "transpose" (ie t() function ) is a different beast: aimed at matrices and with the handy feature of transposing vectors to column-vectors (to allow linear algebra operations for instance).

Interestingly, purrr:transpose also does the same "wrong" thing as base t():

``` r
purrr::transpose(list(1, 2))
#> [[1]]
#> [[1]][[1]]
#> [1] 1
#> 
#> [[1]][[2]]
#> [1] 2
```

<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DavisVaughan** [comment]
fair enough. i think i will keep that error message when `dims(x) > 2`, but fall back to using base R's `t()` function to get the behavior with 1D arrays just to be consistent with what people expect from `t()` based on base R experience.
