### ISSUE TITLE
set_row_names(Titanic, NULL) should set the slot to NULL, not remove it

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/rray#203]
``` r
library(rray); set_row_names(Titanic, NULL)
#> Error in dimnames(x) <- value: length of 'dimnames' [1] not equal to array extent
```

<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by juangomezduaso** [comment]
Whit all the validations you already have in place, perhaps it is safe to do this:
set_dim_names <-function (x, n, nms) 
{
  dim <- rray_dim(x)
  n <- vec_cast(n, integer())
  validate_scalar_n(n)
  validate_requested_dims(x, n)
  nms <- vec_cast(nms, character())
  validate_equal_size_or_no_names(dim[n], vec_size(nms))
  rray_dim_names(x)[n] <- list(nms)              ############ change just here, to admit  NULL
  x
}
