### ISSUE TITLE
A comment about broadcasting vignette

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/rray#216]
In line 40 says:
"In one sentence, the answer is that R _recycles_, but I want it to _broadcast_."
We have a 2x2 crossing here (broadcast , recycle) x (along pos, along axes)  and I think this sentence could perhaps be improved somehow to clarify things.
I am bad counselor about documentation but here are some ideas: 
As it is explained in vctrs, recycling vectors is too much. Broadcasting is the most useful and  meaningful behavior.
The situation with base arrays is that R doesnt recycle along dimensions, only  on the bare vector.
So it does too much and too little at a time.
What  is needed for arrays is just to have broadcasting, but to have it along the dimensions

**Comment by DavisVaughan** [comment]
The real confusion is that R recycles (+ partial recycles) 1D vectors as you say, but does nothing with "recycling" matrices/arrays.

As laid out in the rules a bit later, broadcasting in rray is essentially:
- Match the dimensionality
- For each dimension, perform _tidyverse recycling_ along each dimension

So unfortunately the ideas of R recycling and tidyverse recycling are all mentioned together, in different contexts

**Comment by juangomezduaso** [comment]
Oh you are right. The term used in vctrs is also "recycle",  not "broadcast".

**Comment by DavisVaughan** [comment]
Personally I think those docs are fairly clear, but then again I wrote them. Do you have any suggestions to make them better, or did what I say resolve your original question?

**Comment by juangomezduaso** [comment]
Well, I am neither the best person to judge it, as I am too much inmerse in these concepts ;)
I thought that the introduction in line 40 could be improved, avoiding the names and going straight to the need to broadcast along all axes. But after trying to do it myself, I think that it is not so easy. You stablish the name and gradually through the examples and the rules  the concept will become clear when you read it all as it is now.
 So i will close this issue (at least until some inspiration allows me to contribute in any way).

**Comment by DavisVaughan** [comment]
Yea I think "broadcast along all axes" is the wrong terminology. I think more correct is that broadcasting is sort of like "the act of tidyverse recycling along each axis", plus the nuance that you have to add the implicit dimensionality as needed
