### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/rray#68]
I am trying to install rray and I stumble with these errors in my Win10 machine, with a just installed R 3.5.3 , Rcpp, devtools and the tidyverse.
[consoleError.txt](https://github.com/DavisVaughan/rray/files/3050850/consoleError.txt)

**Comment by DavisVaughan** [comment]
Do you have git? It can't seem to find it when installing xtensor. The file controlling that is here https://github.com/QuantStack/Xtensor.R/blob/master/tools/vendor

**Comment by juangomezduaso** [comment]
That was it.  
I didn't have git in this machine, and, once installed, I was ale to install rray
Thanks!

**Comment by DavisVaughan** [comment]
Happy to hear it. I think this is the first time a Windows install has been tried so I'm glad it looks to have worked

**Comment by juangomezduaso** [comment]
Well, I am not very skilled with C++ , git and low level software installations intrincacities, but feel free to ask me to try whatever you want  on my installation. 
As far as you patiently prescribe exactly what you want me to do ;)

**Comment by DavisVaughan** [comment]
For now, any feedback on how the package "feels" as a whole would be great. Bugs are to be expected for the moment
