### ISSUE TITLE
meta dimnames conservation

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/rray#69]
As pointed out in the "The rray" vignette, rray operations keep as much information as posible regarding dimnames. The same does not happen with the names of dimnames though. 
I think this is not a really important issue, as long as, in practice, the array with the most/best dimnames information is usually the one with meta dimnames as well.
Of all the situations that are possible, an example like the following is the best I can think of as motivation to bother with the introduction of a "coalesce_meta_dimnames" function or functionality in rray:

x <-as_rray( matrix(1:2, dimnames = list(c("r1", "r2"),"c1")) )
y <-as_rray( matrix(1:2, dimnames = list(A=c("r1", "r2"),B="c1")) )
#Here, 
x+y # loses the meta names information available, while ...
y+x # keeps them

**Comment by DavisVaughan** [comment]
Ah yes I'll fix that. Thanks!

BTW have you used the reprex package before? It makes it much easier for me to help you if you use it to make easily reproducible examples! https://community.rstudio.com/t/video-reproducible-examples-and-the-reprex-package/14732

**Comment by juangomezduaso** [comment]
No, I had heard about it but haven't used it yet. 
I'll have a look Thanks.
But I wont need it for the question that I have right now and was about to ask you:
 Is index selection limited to integer indexes in rray?
I was elaborating some comments about brackets and selection  when I realized of this. 
I presume perhaps rray:::`[.vctrs_rray` is a transitory partial implementation to be completed later
 Or am I missing something?

**Comment by DavisVaughan** [comment]
Oh you can use character vectors. The fact that you can't use them for rows is currently a vctrs bug. I'll report that.

``` r
library(rray)

x <- rray(
  1:2, 
  dim = c(2, 1, 2), 
  dim_names = list(c("r1", "r2"), "c1", c("d1", "d2"))
)

x["r1",]
#> Error: Can't use character to index an unnamed vector.

x[,"c1"]
#> <vctrs_rray<integer>[,1,2][4]>
#> , , d1
#> 
#>    c1
#> r1  1
#> r2  2
#> 
#> , , d2
#> 
#>    c1
#> r1  1
#> r2  2

x[,,"d1"]
#> <vctrs_rray<integer>[,1,1][2]>
#> , , d1
#> 
#>    c1
#> r1  1
#> r2  2

x[1,,c("d1", "d2")]
#> <vctrs_rray<integer>[,1,2][2]>
#> , , d1
#> 
#>    c1
#> r1  1
#> 
#> , , d2
#> 
#>    c1
#> r1  1
```

<sup>Created on 2019-04-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by juangomezduaso** [comment]
Ok, yes, I had tryed only the first (and special) one
