### ISSUE TITLE
Rewrite [ and [<-

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/rray#72]
Can probably simplify by removing i,j from [ and then building an expression with the right number of missing args.

For [<- we should also build the assignment expression so x[1,] doesn't fail on 3D arrays and is expanded to x[1,,]

**Comment by DavisVaughan** [comment]
Can probably use the same expression generating engine for both, having an option for whether or not to include drop=FALSE in the expression.

**Comment by DavisVaughan** [comment]
Should [<- fully broadcast value to the dim of x[...]? Currently it just does the shape not the size

**Comment by juangomezduaso** [comment]
I should wait to have a deeper understanding of rray, but as you are considering alternatives, I will post these design thougths on subsetting: 
1) I am not fully confortable with the idea of loosing the bare vector indexing (no commas, unique index argument interpreted as a selection on the subyacent vector of the array) available in base array. I think rray should be able to achieve things like, say, ` X[is.na(X)] <- 0` easily. Sometimes you will want to select cells based not on their position but on their values, and for this, the bare vector access is convenient.
2) Allowing partial omision of dimensions (commas) in the argument list (as long as they are in the tail) seems kind of strange to me. I am probably not getting the point of this design yet. I am neither a fan of the lists of comma separated blanks that are necesary in base array, but this seems to me like half a solution to this issue (more on this below). Perhaps you have other reasons I wasnt able to see yet.

3) IMO, brackets subsetting should be as friendly a function as possible for direct use by the final user (data analyst) and so, formula clarity and expresivity should be a main concern. 
For this goal, my idea would be to allow the use of the metadimnames as names for the arguments of `[()`. If we had an rray with metadimnames and all were valid R identifiers (for instance: Time, Space, or even backquoting as in   `` `Interest Rate` ``  ), I would allow subsetting expressions like this one:
` MyRray[Time=c("2017","2018")] ` 
or with more than one dim at a time:
` MyRray[Time=c("2017","2018"),Space="NY"] `
Introducing the techniques of dplyr, even nicer things like: 
` MyRray[Time=2017:2018,Space=NC:NY] `
would be possible.
This may seem an excesive departure from the conventions in base arrays function, but as there arent many named parameters in [() and friends (left alone "drop") it is tempting to take advantage of this and be able to write formulae with expressions as concise and clear like the ones above.
And, if you think about it, what we would do is just a recognition that the dots in [() are not an arbitrary list: they really refer to each dimension in the array, and so metadimnames are the natural names for these parameters, and we would be matching the arguments to them following just the same (mix of named and positional) algorithm of R functions.
4)  For programing, specially very generic programs,  I think the best is to have a different function that subsets on just one dimension at a time (slice? ). The dimension to operate on would be specified by metadimname or numeric position. For example: ` rray_slice(myrray, "Time",c("2017","2018")) `

**Comment by DavisVaughan** [comment]
> I think rray should be able to achieve things like, say, X[is.na(X)] <- 0 easily.

This seems reasonable. I do think that `x[<singlething>]` should do something. I haven't quite determined exactly what that is yet though. Base R allows full matrices / arrays to be that `<singlething>`. That is what happens in `X[is.na(X)]`. But strange things happen if those indexers don't have exactly the same shape as `x`.

 > Allowing partial omision of dimensions (commas) in the argument list (as long as they are in the tail) seems kind of strange to me.

Does this not feel natural to you? I like it over the base R way.

``` r
library(rray)
x <- rray(1:8, c(2,2,2), dim_names = list(r = c("r1", "r2"), c = c("c1", "c2"), d = c("d1", "d2")))

# x[1, , , drop=FALSE]
x[1,]
#> <vctrs_rray<integer>[,2,2][4]>
#> , , d = d1
#> 
#>     c
#> r    c1 c2
#>   r1  1  3
#> 
#> , , d = d2
#> 
#>     c
#> r    c1 c2
#>   r1  5  7

# x[, 1, , drop = FALSE]
x[,1]
#> <vctrs_rray<integer>[,1,2][4]>
#> , , d = d1
#> 
#>     c
#> r    c1
#>   r1  1
#>   r2  2
#> 
#> , , d = d2
#> 
#>     c
#> r    c1
#>   r1  5
#>   r2  6

# x[, , 1, drop = FALSE]
x[,,1]
#> <vctrs_rray<integer>[,2,1][4]>
#> , , d = d1
#> 
#>     c
#> r    c1 c2
#>   r1  1  3
#>   r2  2  4
```

> use of the metadimnames as names for the arguments 

This feels like a nice idea on the surface, but I'm worried about how complicated it might get. For instance, `MyRray[Time=2017:2018,Space=NC:NY]` are you selecting rows 2017 and 2018? Or looking for rownames `"2017"` and `"2018"`?

More generally, for `MyRray[Time=c("2017","2018"),Space="NY"]`. This would have a clear meaning, "select elements with names 2017 and 2018 from the dimension with meta name, Time, and select elements with name NY from the dimension with meta name, Space". I'm just a bit worried about how users will feel if those are not the first and second dimensions, respectively. Like, if those are the third and fourth dimensions is that confusing? Also, what happens if multiple dimensions happened to both have the meta name `"Time"`? There isn't really anything saying that can't happen, and I'm not sure what it would do there.

> I think the best is to have a different function that subsets on just one dimension at a time (slice? )

I do like this idea. `rray_slice(x, axis = "Time", index = c("2017", "2018"))` or `rray_slice(x, axis = 4, index = 1:2)` which would nicely be equivalent to `x[, , , 1:2]`

**Comment by DavisVaughan** [comment]
Should an rray be able to do this?

``` r
x <- matrix(1:6, c(2, 3))
x[1:3] <- 99
x
#>      [,1] [,2] [,3]
#> [1,]   99   99    5
#> [2,]   99    4    6
```

Something feels wrong about that. But like you said, you want to be able to do:

``` r
x <- matrix(c(1, 2, NA, NA, 5, 6), c(2, 3))

is.na(x)
#>       [,1] [,2]  [,3]
#> [1,] FALSE TRUE FALSE
#> [2,] FALSE TRUE FALSE

x[is.na(x)] <- 0
x
#>      [,1] [,2] [,3]
#> [1,]    1    0    5
#> [2,]    2    0    6
```

Maybe we should allow `x[<something>]`, with the restriction that `<something>` is a logical that either already has the same shape as `x` or is broadcast to the same shape as `x`.
