### ISSUE TITLE
Bind default axis

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/rray#79]
Not an important issue. Just call your attention to the default valueof rray_bind(). Having special functions for row and column binding in rray why don't give axis a different default value in this one? Packages take different options: abind choosed length(dim(x)). narray prefered  length(dim(x))+1. Both "favour" bindings that dont need to interleave (just concatenate the values), but this is almost irrelevant

**Comment by DavisVaughan** [comment]
I think I'm more tempted to remove the default altogether, and force the user to be explicit about what axis they are binding over. If they want the shortcuts they can use `rray_rbind()` / `rray_cbind()` which allows them to be explicit in a different way.

**Comment by DavisVaughan** [comment]
Closed by #91
