### ISSUE TITLE
newaxis() in subsetting

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/rray#87]
With xt::newaxis(). Have to decide on an R sentinal value

**Comment by juangomezduaso** [comment]
[Excuse me if this is not what you were thinking about in this issue, I have no idea of xtensor yet.]
Perhaps rray could use the param names to signal the insertion:
x[ , , newaxis= , ]  
with missing argument. Or with optional metadata:
x[ , , newaxis=list(Time="2017") , ]

**Comment by DavisVaughan** [comment]
It would be more of `x[, new_axis(), 1, 2]` which would insert a new 2nd dimension axis and bump the current 2nd and 3rd dimension up to 3rd and 4th dimensions respectively. I haven't decided yet if it is the right approach. It is used a lot in numpy to correct their behavior of having things like `sum()` drop dimensions (so then you can broadcast correctly against `x` with it), but `rray_sum()` doesn't do that so the correction isn't needed. It is somewhat identical to using `rray_expand_dims(x, 2)` before subsetting.

**Comment by DavisVaughan** [comment]
Closing for now as I haven't felt that I needed it so far
