### ISSUE TITLE
Pronouns

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/rray#94]
Wouldn't it be worth it to have a pronoun assigned to the current rray being subsetted in a bracket expresion? (something like the ".data" in dplyr)
When the rray is not given by an identifier but as a result of a call, any repetition of it in the indexes can be painful
Perhaps other pronouns like the dim of the rray, the dim of the current axis or the current axis number itself could also be interesting.

**Comment by DavisVaughan** [comment]
Can you show code for an example of where it would be useful?

**Comment by juangomezduaso** [comment]
I meant expressions in which the indexes depend on some computation involving the rray. 
Something like:
`x[ , rray_sum(x, 2) > 0 ,  1]`
is simple, but if  instead of the name "x" we had the result of a call, say:
`rray_abs((A-B)/2)[ , rray_sum(rray_abs((A-B)/2), 2) > 0 ,  1]`
the formula becomes difficult to write and read, repeats computation and is error prone
One can always do an assignment, but it is not optimal if we wont need that variable anymore
It would be good to have a pronoun, say "**.Ry**" to alow:
`rray_abs((A-B)/2)[  , rray_sum(.Ry, 2) > 0 ,  1]`

**Comment by juangomezduaso** [comment]
The other pronouns are less clear. Just speculations derived from the initial goal of this issue, that was to propose ways to substitute the functionality of indices that start from the tail of an axis. In Python they have negative indexes, but in R this is used for exclusion, not for axis reversion.
But I then realized that exclusion and rray_flip() are enough for these needs. 
The current dim pronoun (say **.DIM**) seemed usefull ayway, for cases where it were involved in calculations:
`x[ , ,  1 :floor(.DIM/3), ,]`

**Comment by juangomezduaso** [comment]
In assignment subsetting there is a potencial for ambiguity thogh. There may be another rray on the right hand side and It is not clear to which one the pronoun points to

**Comment by juangomezduaso** [comment]
The more I think of this issue the more unsecure I am. In fact, the pronoun that I now think is more useful in assignment is neither the left or right rray, but the left hand side selection. The pattern:
x[indexes] <- x[indexes] + something
 for instance, is quite common , and a pronoun "left hand side" would simplify it to:
x[indexes] <- .LHS + something
This pattern reminds me of the += C operator.  A syntax to implement it in R for our purpose could be:
x[indexes] <- %+% something
Anyway, the whole idea of pronouns and special evaluations, suggestive as it may be, isn't well thought out and I am sorry I comented it too soon.
So I will close this issue, at least for the moment
